# Generated by Django 4.2.7 on 2024-01-01 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2024, 1, 1))),
                ('category', models.CharField(max_length=100)),
                ('memo', models.CharField(max_length=100)),
                ('income', models.IntegerField(default=0)),
                ('expenditure', models.IntegerField(default=0)),
            ],
        ),
    ]
